FROM node:18.15.0

ARG DATABASE_URL
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET

ENV DATABASE_URL=${DATABASE_URL}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
ENV GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

WORKDIR /usr/src/app
COPY prisma ./prisma/
COPY package*.json ./
RUN npm install
RUN npm install -g pnpm 
COPY . ./
RUN pnpm next build
RUN npx prisma generate --schema ./prisma/schema.prisma
RUN chmod +x ./migrate-and-start.sh
ENV PORT=3000
EXPOSE 3000
CMD ["./migrate-and-start.sh"]
